### ISSUE TITLE
progress and documentation

### ISSUE THREAD

**Issue by amaterasushen** [BlackMesa123/UN1CA#1]
Goodnight.

I found your project extremely interesting, I would like to know the progress of the project and whether it is close to being completed.

I would like to know if you will make documentation for those who want to port it to new devices, for example I would like to do it for my S10 Lite. I was able to boot the stock A52s 5G on my S10 lite without too many changes, so I imagine a port to my device would be relatively easy.

Is there a channel or group on Telegram to ask questions or talk about?

:)

**Comment by BlackMesa123** [comment]
Hi there, thanks for the interest in the project.
With the tree at the time of writing (a2666a81a3fd3fe38cdfa393d1f97f20699c8905), the build system is able to automatically download, extract, apply the mods/required patches, repack as flashable zip for the two devices I've been working on lately (A52s and M52, both having 778G/yupik):

<img src="https://github.com/BlackMesa123/UN1CA/assets/13062958/82b7f57d-d038-45c3-a263-6835187d4215" width="30%"/> <img src="https://github.com/BlackMesa123/UN1CA/assets/13062958/2d836aea-e380-44f4-8126-caf0bc7155e0" width="30%"/>

However, this is still far than complete unfortunately. I'll be opening up a few issues describing the status of certain elements of the project that needs to be improved/created as well as device-specific bugs I'm still struggling with.

If you do have any questions, do not hesitate asking.

**Comment by amaterasushen** [comment]
What are the construction dependencies? and which distro do you recommend? I had problems with cmake on Linux Mint, it gives me an error even though it generates config.sh.

I want to do it for the a52 first to see how it behaves and port it to my device since it's similar to the a52s.

**Comment by BlackMesa123** [comment]
You can find a list of the required dependencies in the GH Actions CI workflow:
https://github.com/BlackMesa123/UN1CA/blob/97e369ebdea9a635ee05d380a3df22ba0ad55bae/.github/workflows/build.yml#L29-L31
Java **11** is also required.

**Comment by amaterasushen** [comment]
> You can find a list of the required dependencies in the GH Actions CI workflow:
> 
> https://github.com/BlackMesa123/UN1CA/blob/97e369ebdea9a635ee05d380a3df22ba0ad55bae/.github/workflows/build.yml#L29-L31
> 
> Java **11** is also required.

I tried a build for the a52s and got this error:

`fl-vio-amorim@fl-vio:~/UN1CA$ source ./buildenv.sh a52sxq
- Building android-tools...

-- Applying patches for: adb
fatal: previous rebase directory /home/fl-vio-amorim/UN1CA/.git/modules/external/android-tools/rebase-apply still exists but mbox given.
CMake Error at vendor/CMakeLists.txt:58 (message):
  Couldn't apply patches for adb


-- Configuring incomplete, errors occurred!
==============================
ROM_IS_OFFICIAL=false
SOURCE_FIRMWARE=SM-S911B/BTE
SOURCE_API_LEVEL=34
SOURCE_VNDK_VERSION=33
TARGET_CODENAME=a52sxq
TARGET_FIRMWARE=SM-A528B/BTU
TARGET_API_LEVEL=34
TARGET_VNDK_VERSION=30
TARGET_SINGLE_SYSTEM_IMAGE=qssi
TARGET_OS_FILE_SYSTEM=ext4
TARGET_SUPER_PARTITION_SIZE=10643046400
TARGET_SUPER_GROUP_SIZE=10638852096
SOURCE_HAS_SYSTEM_EXT=true
TARGET_HAS_SYSTEM_EXT=false
SOURCE_HAS_MASS_CAMERA_APP=false
TARGET_HAS_MASS_CAMERA_APP=true
SOURCE_HAS_OPTICAL_FP_SENSOR=false
TARGET_HAS_OPTICAL_FP_SENSOR=true
SOURCE_IS_ESIM_SUPPORTED=true
TARGET_IS_ESIM_SUPPORTED=false
==============================
`

**Comment by amaterasushen** [comment]
> You can find a list of the required dependencies in the GH Actions CI workflow:
> 
> https://github.com/BlackMesa123/UN1CA/blob/97e369ebdea9a635ee05d380a3df22ba0ad55bae/.github/workflows/build.yml#L29-L31
> 
> Java **11** is also required.

I can't solve this problem, do you have any ideas?

`CMake Error at /usr/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/home/flavio/work/UN1CA/external/erofs-utils/out/CMakeFiles/CMakeScratch/TryCompile-BPb1Jn'
    
    Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_8e834/fast
    /usr/bin/gmake  -f CMakeFiles/cmTC_8e834.dir/build.make CMakeFiles/cmTC_8e834.dir/build
    gmake[1]: Entering directory '/home/flavio/work/UN1CA/external/erofs-utils/out/CMakeFiles/CMakeScratch/TryCompile-BPb1Jn'
    Building CXX object CMakeFiles/cmTC_8e834.dir/testCXXCompiler.cxx.o
    /usr/bin/clang++    -MD -MT CMakeFiles/cmTC_8e834.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_8e834.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_8e834.dir/testCXXCompiler.cxx.o -c /home/flavio/work/UN1CA/external/erofs-utils/out/CMakeFiles/CMakeScratch/TryCompile-BPb1Jn/testCXXCompiler.cxx
    Linking CXX executable cmTC_8e834
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8e834.dir/link.txt --verbose=1
    /usr/bin/clang++ CMakeFiles/cmTC_8e834.dir/testCXXCompiler.cxx.o -o cmTC_8e834 
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_8e834.dir/build.make:100: cmTC_8e834] Error 1
    gmake[1]: Leaving directory '/home/flavio/work/UN1CA/external/erofs-utils/out/CMakeFiles/CMakeScratch/TryCompile-BPb1Jn'
    gmake: *** [Makefile:127: cmTC_8e834/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
`

**Comment by amaterasushen** [comment]
I have a question, does this a52sxq debloat list remove files from the S23 stock? Do you have any tips for debloat? my super partition is only 8gb.

**Comment by amaterasushen** [comment]
> > I have a question, does this a52sxq debloat list remove files from the S23 stock? Do you have any tips for debloat? my super partition is only 8gb.
> 
> Only the vendor partition is from the target device, all the rest is from the source firmware (Galaxy S23). The project has two separate debloat lists, A52s one only removes useless system services.

my device doesn't have "vendor.samsung.hardware.biometrics.face@3.0.so" on system_ext and I don't know how to resolve this in the script.

**Comment by amaterasushen** [comment]
- Recompiling APKs/JARs...
Recompiling /system/framework/services.jar
out/apktool/system/framework/services.jar/smali_classes2/com/android/server/locksettings/LockSettingsService.smali[17800,4] There is already a label with that name.
Could not smali file: com/android/server/locksettings/LockSettingsService.smali

but clearly there is a LockSettingsService.smali in smali_classes2/com/android/server/locksettings/LockSettingsService.smali

**Comment by BlackMesa123** [comment]
> my device doesn't have "vendor.samsung.hardware.biometrics.face@3.0.so" on system_ext and I don't know how to resolve this in the script.

You don't have to copy/paste the A52s config/patches as-it-is, instead you should make specific patches made for your and only your device where required

**Comment by BlackMesa123** [comment]
> - Recompiling APKs/JARs...
> 
> Recompiling /system/framework/services.jar
> 
> out/apktool/system/framework/services.jar/smali_classes2/com/android/server/locksettings/LockSettingsService.smali[17800,4] There is already a label with that name.
> 
> Could not smali file: com/android/server/locksettings/LockSettingsService.smali
> 
> 
> 
> but clearly there is a LockSettingsService.smali in smali_classes2/com/android/server/locksettings/LockSettingsService.smali

In fact the error mentions an issue in line "17800", it doesn't says the file doesn't exists

**Comment by amaterasushen** [comment]
> > * Recompilando APKs/JARs...
> > 
> > Recompilando /system/framework/services.jar 
> > out/apktool/system/framework/services.jar/smali_classes2/com/android/server/locksettings/LockSettingsService.smali[17800,4] Já existe um rótulo com esse nome. 
> > Não foi possível smali arquivo: com/android/server/locksettings/LockSettingsService.smali 
> > mas claramente há um LockSettingsService.smali em smali_classes2/com/android/server/locksettings/LockSettingsService.smali
> 
> Na verdade, o erro menciona um problema na linha "17800", não diz que o arquivo não existe

I'm in bootloop. any tips?
