### ISSUE TITLE
BixbyVisionFramework3.5 removed unconditionally from fs config/context files  

### ISSUE THREAD

**Issue by Fede2782** [BlackMesa123/UN1CA#37]
Even if BixbyVisionFramework3.5 is not in debloat list it is removed from file_context and fs_config when in the debloat list there is the main Bixby package. I don't know if this is a normal behiavour of the debloat script

**Comment by BlackMesa123** [comment]
Do you have a full log of the build to share so I can check where exactly the debloat happens?

**Comment by Fede2782** [comment]
[apply_debloat_log.txt](https://github.com/BlackMesa123/UN1CA/files/13759156/apply_debloat_log.txt)

If I use the make_rom command the script stops when building system images, after product the script simply exists without any error. If you need other parts of the log I can send you them

**Comment by BlackMesa123** [comment]
Basing on the logs, only the odex folder gets deleted (`Debloating /system/system/priv-app/BixbyVisionFramework3.5/oat`).
You can debug why system img doesn't builds by building it manually via the `build_fs_image` command:
```bash
run_cmd build_fs_image ext4 ./out/work_dir/system ./out/work_dir/configs/file_context-system ./out/work_dir/configs/fs_config-system
```

**Comment by Fede2782** [comment]
I'm trying it right now

**Comment by Fede2782** [comment]
It worked at 2nd try because I had to add BixbyVisionIntelligence entries before in order to solve the error

**Comment by BlackMesa123** [comment]
Are you actually able to see in the build logs if this folder actually gets deleted by the build system somewhere? Debloat might also occur in single patches rather than in the main debloat list.

**Comment by Fede2782** [comment]
> Are you actually able to see in the build logs if this folder actually gets deleted by the build system somewhere? Debloat might also occur in single patches rather than in the main debloat list.

The folder doesn't get deleted from work_dir it gets only removed from fs_config/file_context. In device-specific debloat list I added Bixby and BixbyWakeup but not Vision Intelligence, maybe the script removed all occurrences with Bixby at the start of the name.

**Comment by BlackMesa123** [comment]
I see, shouldn't be hard to fix this, I'll issue a PR in a moment.

**Comment by Fede2782** [comment]
The device-specific stock_blobs module also replaces Google Assistant blobs and the script also removes them from fs_config/file_context without adding the new ones. I don't know if this two things are related but the stock_blobs I use is the same as A52s with a small change in camera blobs part
