### ISSUE TITLE
Link down

### ISSUE THREAD

**Issue by Nycolaz1** [BlackMesa123/UN1CA#59]
No loading link

**Comment by autelast** [comment]
+, link down.
![Screenshot_20240113_150046_Chrome](https://github.com/BlackMesa123/UN1CA/assets/153913201/adc862a2-2708-414a-861c-32b11be09a5f)
![Screenshot_20240113_150116_Chrome](https://github.com/BlackMesa123/UN1CA/assets/153913201/d41fbe56-a648-4ba0-b54f-d51eb5e4ee7a)

**Comment by BlackMesa123** [comment]
The server has reached the limit of simultaneous connections yesterday due to the big amount of people trying to download the ROM simultaneously. I upgraded the server to support more simultaneous connections, hoping it is enough for now.

**Comment by autelast** [comment]
> The server has reached the limit of simultaneous connections yesterday due to the big amount of people trying to download the ROM simultaneously. I upgraded the server to support more simultaneous connections, hoping it is enough for now.

Ok👌
