### ISSUE TITLE
Samsung Dex

### ISSUE THREAD

**Issue by ItsMadruga** [BlackMesa123/UN1CA#90]
I'm using your UN1CA from a71 and I noticed that you brought the Samsung Dex for it, would it be possible to get the Samsung Dex on other devices? I have an A54 and I really want this function. Thank you for your attention

**Comment by GabrielARK14** [comment]
> be

un1ca is also available for the a54, I recommend you join the telegram group

**Comment by ItsMadruga** [comment]
> > be
> 
> un1ca is also available for the a54, I recommend you join the telegram group

it still doesn't have a stable version of un1ca, and I'm only interested in the samsung dex, if it's not possible to get it without using the rom, I'll have to wait for a stable one, which was mentioned to only come when one ui 6.1 is released.

**Comment by BlackMesa123** [comment]
Porting DeX on devices that do not have it is time consuming since there are system calls almost everywhere in system, it’s way easier to just port a different system image than the one your device should run.
